spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: admin
    password: admin
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
  devtools:
    restart:
      log-condition-evaluation-delta: false
      livereload:
        enabled: false
        port: 35729